language: cpp
compiler: g++
script:
    make test
git:
    submodules: true
matrix:
    include:
        - os: linux
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - g++-8
          env:
              - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
